version: '3.8'

services:
  vite-app:
    image: node:20-alpine
    container_name: vite-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
