
services:
  app:
    image: aykosn/alugux:latest
    container_name: app
    networks:
      - alugux_net

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:8080
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nginx_logs:/var/log/nginx
    networks:
      - alugux_net

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - --nginx.scrape-uri=http://nginx:8080/status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - alugux_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - alugux_net
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - alugux_net

networks:
  alugux_net:
    driver: bridge

volumes:
  nginx_logs:
  prometheus_data:
  grafana_data:
