services:
  app:
    image: aykosn/alugux:latest
    ports:
      - 8080:8080
    networks:
      - alugux_net
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    networks:
      - alugux_net
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

networks:
  alugux_net:
    driver: bridge