global:
  scrape_interval: "1m" # Intervalo de tempo entre a coleta de métricas
  scrape_timeout: "10s" # Tempo de espera para o endpoint retornar os logs
  evaluation_interval: "1m"
  body_size_limit: "0"
  sample_limit: 0
  label_limit: 0
  label_name_length_limit: 0
  label_value_length_limit: 0
  target_limit: 0

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090