// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jnkjeaulleuxdyxypskc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impua2plYXVsbGV1eGR5eHlwc2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDkzNDcsImV4cCI6MjA1NDYyNTM0N30.GJcYMABrYGQOne2qJxbKvWoDR-uvhxQAcKy4mILx0is";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);